# Generated by Django 4.1 on 2024-06-23 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_foto',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
