# Generated by Django 4.1 on 2024-06-23 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_data_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_foto',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
